[General]

loglevel = notify

[Proxy]

Local-Xray = socks5, 127.0.0.1, 18998, udp-relay=true

[Proxy Group]

Proxy = select, Local-Xray, DIRECT

[Rule]

# Prevent local proxy loop

PROCESS-NAME,xray,DIRECT
PROCESS-NAME,xray-linux-amd64,DIRECT

# Example final routing

FINAL,Proxy
